AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  budget2sheets
  
  SAM Template for budget2sheets app

Parameters:
  GoogleCredentialsSecretARN:
    Type: String
  GoogleSpreadsheetId:
    Type: String
  GoogleSpreadsheetRange:
    Type: String
  InputQueueName:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: provided.al2023
    Timeout: 60
    MemorySize: 512
    Architectures:
      - arm64

Resources:
  
  Budget2SheetsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: bootstrap
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          GOOGLE_CREDENTIALS_SECRET_ARN: !Ref GoogleCredentialsSecretARN
          GOOGLE_SPREADSHEET_ID: !Ref GoogleSpreadsheetId
          GOOGLE_SPREADSHEET_RANGE: !Ref GoogleSpreadsheetRange
      Policies:
      - Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Ref GoogleCredentialsSecretARN
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !Join
                      - ''
                      - - 'arn:aws:sqs:'
                        - !Ref AWS::Region
                        - ':'
                        - !Ref 'AWS::AccountId'
                        - ':'
                        - !Ref InputQueueName
            BatchSize: 5

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: [ Budget2SheetsFunction ] 
    Properties:
        RetentionInDays: 3
        LogGroupName: !Join ['', ['/aws/lambda/', !Ref Budget2SheetsFunction]]

Outputs:
  Budget2SheetsFunction:
    Description: "Budget 2Sheets Lambda Function ARN"
    Value: !GetAtt Budget2SheetsFunction.Arn
  Budget2SheetsFunctionIamRole:
    Description: "Implicit IAM Role created for Budget 2Sheets function"
    Value: !GetAtt Budget2SheetsFunctionRole.Arn
